/*
  This file is automatically generated. Any changes will be overwritten.
  Modify copy-of-erfassen.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { IconComponent } from '@radzen/angular/dist/icon';
import { CardComponent } from '@radzen/angular/dist/card';
import { LabelComponent } from '@radzen/angular/dist/label';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { DataListComponent } from '@radzen/angular/dist/datalist';

import { ConfigService } from '../config.service';
import { ZzErfassenAuswahlLagerorteComponent } from '../zz-erfassen-auswahl-lagerorte/zz-erfassen-auswahl-lagerorte.component';

import { DbOptimoService } from '../db-optimo.service';

export class CopyOfErfassenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('icon2') icon2: IconComponent;
  @ViewChild('card0') card0: CardComponent;
  @ViewChild('heading0') heading0: HeadingComponent;
  @ViewChild('heading3') heading3: HeadingComponent;
  @ViewChild('icon0') icon0: IconComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('icon1') icon1: IconComponent;
  @ViewChild('textbox1') textbox1: TextBoxComponent;
  @ViewChild('label5') label5: LabelComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('label3') label3: LabelComponent;
  @ViewChild('textbox2') textbox2: TextBoxComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;
  @ViewChild('button3') button3: ButtonComponent;
  @ViewChild('buttonKontakteSpeichern') buttonKontakteSpeichern: ButtonComponent;
  @ViewChild('card3') card3: CardComponent;
  @ViewChild('button4') button4: ButtonComponent;
  @ViewChild('tabs1') tabs1: TabsComponent;
  @ViewChild('card1') card1: CardComponent;
  @ViewChild('label6') label6: LabelComponent;
  @ViewChild('datalistLagerorteArtikel') datalistLagerorteArtikel: DataListComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('buttonOpenDialogAuswahlLagerorte') buttonOpenDialogAuswahlLagerorte: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;
  dsoLagerort: any;
  onClickAuswahlLagerorte: any;
  parameters: any;
  rstLagerorteArtikel: any;
  rstLagerorteArtikelCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    window.scroll(0,0);

    this.dbOptimo.getInventurBases(`InventurID eq ${this.parameters.InventurID}`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.dsoLagerort = result.value[0];
    }, (result: any) => {

    });

    this.datalistLagerorteArtikel.load();

    this.onClickAuswahlLagerorte = () => {
    this.buttonOpenDialogAuswahlLagerorteClick('');
};
  }

  datalistLagerorteArtikelLoadData(event: any) {
    this.dbOptimo.getInventurArtikels(`InventurID eq 100016`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstLagerorteArtikel = result.value;

      this.rstLagerorteArtikelCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  buttonOpenDialogAuswahlLagerorteClick(event: any) {
    this.dialogService.open(ZzErfassenAuswahlLagerorteComponent, { parameters: {}, title: `Auswahl Lagerorte` })
        .afterClosed().subscribe(result => {
              if (result != null) {
              this.dbOptimo.getInventurBases(`InventurID eq ${result}`, null, null, null, null, null, null, null)
        .subscribe((result: any) => {
              this.dsoLagerort = result.value[0];
        }, (result: any) => {
      
        });
      }
    });
  }
}
