/*
  This file is automatically generated. Any changes will be overwritten.
  Modify device-registrieren.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { DataListComponent } from '@radzen/angular/dist/datalist';
import { CardComponent } from '@radzen/angular/dist/card';
import { LabelComponent } from '@radzen/angular/dist/label';
import { IconComponent } from '@radzen/angular/dist/icon';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';
import { MeldungJaNeinComponent } from '../meldung-ja-nein/meldung-ja-nein.component';

import { DbOptimoService } from '../db-optimo.service';

export class DeviceRegistrierenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('datalistDevice') datalistDevice: DataListComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('buttonDeviceRegistrieren') buttonDeviceRegistrieren: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;
  onClickDeviceRegistrieren: any;
  parameters: any;
  rstDevice: any;
  rstDeviceCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.datalistDevice.load();

    this.onClickDeviceRegistrieren = (data) => {
    this.buttonDeviceRegistrierenClick(data);
};
  }

  datalistDeviceLoadData(event: any) {
    this.dbOptimo.getInventurDevices(null, null, null, `DeviceNummer`, null, null, null, null)
    .subscribe((result: any) => {
      this.rstDevice = result.value;

      this.rstDeviceCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  buttonDeviceRegistrierenClick(event: any) {
    if (event.RegistriertAm != null) {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Dieses Gerät ist bereits registriert!` });
    }

    if (event.RegistriertAm == null) {
      this.dialogService.open(MeldungJaNeinComponent, { parameters: {strMeldung: "Soll das ausgewählte Gerät '" + event.DeviceNummer + "' registriert werden?"}, title: `Gerät registrieren` })
          .afterClosed().subscribe(result => {
                  if (result == 'Ja') {
          var date = new Date();

event.RegistriertAm = new Date(Date.UTC(date.getFullYear(),
                                         date.getMonth(),
                                         date.getDate(),
                                         date.getHours(),
                                         date.getMinutes(),
                                         date.getSeconds(),
                                         date.getMilliseconds() ));
                                         
event.AnmeldungAm = null;
event.AbmeldungAm = null;
        }

        if (result == 'Ja') {
                  this.dbOptimo.updateInventurDevice(null, event.DeviceID, event)
          .subscribe((result: any) => {
                  this.notificationService.notify({ severity: "success", summary: ``, detail: `Gerät registriert` });

          localStorage.setItem("globalDeviceID", event.DeviceID)

          if (this.dialogRef) {
            this.dialogRef.close();
          } else {
            this._location.back();
          }
          }, (result: any) => {
                  this.notificationService.notify({ severity: "error", summary: ``, detail: `Gerät konnte nicht registriert werden!` });
          });
        }
      });
    }
  }
}
