/*
  This file is automatically generated. Any changes will be overwritten.
  Modify erfassen-artikel-auswahl.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { IconComponent } from '@radzen/angular/dist/icon';
import { LabelComponent } from '@radzen/angular/dist/label';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { DataListComponent } from '@radzen/angular/dist/datalist';
import { CardComponent } from '@radzen/angular/dist/card';
import { HeadingComponent } from '@radzen/angular/dist/heading';

import { ConfigService } from '../config.service';

import { DbOptimoService } from '../db-optimo.service';

export class ErfassenArtikelAuswahlGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('icon0') icon0: IconComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('textboxArtikelSuchen') textboxArtikelSuchen: TextBoxComponent;
  @ViewChild('buttonArtikelSuchen') buttonArtikelSuchen: ButtonComponent;
  @ViewChild('datalistArtikel') datalistArtikel: DataListComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;
  onClickSetArtikel: any;
  onClickNavigateBack: any;
  parameters: any;
  rstArtikel: any;
  rstArtikelCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.datalistArtikel.load();

    this.onClickSetArtikel = (data) => {
    this.dialogRef.close(data.ArtikelID);
};

    this.onClickNavigateBack = () => {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this._location.back();
};
  }

  datalistArtikelLoadData(event: any) {
    this.dbOptimo.getInventurArtikels(null, 50, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstArtikel = result.value;

      this.rstArtikelCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }
}
