/*
  This file is automatically generated. Any changes will be overwritten.
  Modify copy-of-dashboard-2.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { CardComponent } from '@radzen/angular/dist/card';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { ProgressBarComponent } from '@radzen/angular/dist/progressbar';
import { DataListComponent } from '@radzen/angular/dist/datalist';
import { IconComponent } from '@radzen/angular/dist/icon';
import { LabelComponent } from '@radzen/angular/dist/label';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { LinkComponent } from '@radzen/angular/dist/link';

import { ConfigService } from '../config.service';

import { DbOptimoService } from '../db-optimo.service';

export class CopyOfDashboard2Generated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('card4') card4: CardComponent;
  @ViewChild('heading3') heading3: HeadingComponent;
  @ViewChild('heading4') heading4: HeadingComponent;
  @ViewChild('progressbar1') progressbar1: ProgressBarComponent;
  @ViewChild('card7') card7: CardComponent;
  @ViewChild('heading10') heading10: HeadingComponent;
  @ViewChild('heading11') heading11: HeadingComponent;
  @ViewChild('progressbar2') progressbar2: ProgressBarComponent;
  @ViewChild('datalistLagerorte') datalistLagerorte: DataListComponent;
  @ViewChild('card2') card2: CardComponent;
  @ViewChild('icon1') icon1: IconComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('label1') label1: LabelComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('card1') card1: CardComponent;
  @ViewChild('icon0') icon0: IconComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('card6') card6: CardComponent;
  @ViewChild('icon2') icon2: IconComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('card3') card3: CardComponent;
  @ViewChild('icon3') icon3: IconComponent;
  @ViewChild('button3') button3: ButtonComponent;
  @ViewChild('heading5') heading5: HeadingComponent;
  @ViewChild('card5') card5: CardComponent;
  @ViewChild('icon5') icon5: IconComponent;
  @ViewChild('button5') button5: ButtonComponent;
  @ViewChild('heading7') heading7: HeadingComponent;
  @ViewChild('card8') card8: CardComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('link0') link0: LinkComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;
  dateHeute: any;
  onClickStartBenutzer: any;
  onClickLagerortInventur: any;
  parameters: any;
  rstLagerorte: any;
  rstLagerorteCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dateHeute = new Date();

    this.onClickStartBenutzer = () => {
    console.log("onClick...")
};

    this.datalistLagerorte.load();

    this.onClickLagerortInventur = (data) => {
    console.log("onClickLagerortInventur...", data)
};
  }

  datalistLagerorteLoadData(event: any) {
    this.dbOptimo.getInventurBases(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstLagerorte = result.value;

      this.rstLagerorteCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  button0Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['kontakte']);

    window.scroll(0,0);
  }

  button1Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['nachrichten']);

    window.scroll(0,0);
  }

  button3Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['nachrichten']);

    window.scroll(0,0);


  }

  button5Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['einstellungen']);

    window.scroll(0,0);
  }
}
