/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { HeaderModule } from '@radzen/angular/dist/header';
import { ImageModule } from '@radzen/angular/dist/image';
import { LabelModule } from '@radzen/angular/dist/label';
import { BodyModule } from '@radzen/angular/dist/body';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { IconModule } from '@radzen/angular/dist/icon';
import { ContentModule } from '@radzen/angular/dist/content';
import { DataListModule } from '@radzen/angular/dist/datalist';
import { CardModule } from '@radzen/angular/dist/card';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { ButtonModule } from '@radzen/angular/dist/button';
import { TabsModule } from '@radzen/angular/dist/tabs';
import { HtmlModule } from '@radzen/angular/dist/html';
import { ProgressBarModule } from '@radzen/angular/dist/progressbar';
import { SparklineModule } from '@radzen/angular/dist/sparkline';
import { LinkModule } from '@radzen/angular/dist/link';
import { TextBoxModule } from '@radzen/angular/dist/textbox';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { InfosComponent } from './infos/infos.component';
import { ZzDashboardV1Component } from './zz-dashboard-v-1/zz-dashboard-v-1.component';
import { ErfassenComponent } from './erfassen/erfassen.component';
import { ZzDashboardV2Component } from './zz-dashboard-v-2/zz-dashboard-v-2.component';
import { ZzErfassenAuswahlLagerorteComponent } from './zz-erfassen-auswahl-lagerorte/zz-erfassen-auswahl-lagerorte.component';
import { ZzDashboardV3Component } from './zz-dashboard-v-3/zz-dashboard-v-3.component';
import { InventurStartLayoutComponent } from './inventur-start-layout/inventur-start-layout.component';
import { InventurInfosLayoutComponent } from './inventur-infos-layout/inventur-infos-layout.component';
import { InventurErfassenLayoutComponent } from './inventur-erfassen-layout/inventur-erfassen-layout.component';

import { DbOptimoService } from './db-optimo.service';

export const PageDeclarations = [
  DashboardComponent,
  InfosComponent,
  ZzDashboardV1Component,
  ErfassenComponent,
  ZzDashboardV2Component,
  ZzErfassenAuswahlLagerorteComponent,
  ZzDashboardV3Component,
];

export const LayoutDeclarations = [
  InventurStartLayoutComponent,
  InventurInfosLayoutComponent,
  InventurErfassenLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  DbOptimoService,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  HeaderModule,
  ImageModule,
  LabelModule,
  BodyModule,
  ContentContainerModule,
  IconModule,
  ContentModule,
  DataListModule,
  CardModule,
  HeadingModule,
  ButtonModule,
  TabsModule,
  HtmlModule,
  ProgressBarModule,
  SparklineModule,
  LinkModule,
  TextBoxModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
