/*
  This file is automatically generated. Any changes will be overwritten.
  Modify erfassen.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { LabelComponent } from '@radzen/angular/dist/label';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { IconComponent } from '@radzen/angular/dist/icon';
import { DataListComponent } from '@radzen/angular/dist/datalist';
import { CardComponent } from '@radzen/angular/dist/card';

import { ConfigService } from '../config.service';
import { ZzErfassenAuswahlLagerorteComponent } from '../zz-erfassen-auswahl-lagerorte/zz-erfassen-auswahl-lagerorte.component';
import { ErfassenArtikelAuswahlComponent } from '../erfassen-artikel-auswahl/erfassen-artikel-auswahl.component';

import { DbOptimoService } from '../db-optimo.service';

export class ErfassenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('label1') label1: LabelComponent;
  @ViewChild('textbox1') textbox1: TextBoxComponent;
  @ViewChild('buttonArtikelAuswahl') buttonArtikelAuswahl: ButtonComponent;
  @ViewChild('label4') label4: LabelComponent;
  @ViewChild('label6') label6: LabelComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('label3') label3: LabelComponent;
  @ViewChild('textbox2') textbox2: TextBoxComponent;
  @ViewChild('button2') button2: ButtonComponent;
  @ViewChild('heading6') heading6: HeadingComponent;
  @ViewChild('heading7') heading7: HeadingComponent;
  @ViewChild('label5') label5: LabelComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('icon4') icon4: IconComponent;
  @ViewChild('datalistLagerorte') datalistLagerorte: DataListComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('buttonOpenDialogAuswahlLagerorte') buttonOpenDialogAuswahlLagerorte: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;
  dsoLagerort: any;
  onClickAuswahlLagerorte: any;
  parameters: any;
  rstLagerorte: any;
  rstLagerorteCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    window.scroll(0,0);

    this.dbOptimo.getInventurBases(`InventurID eq ${this.parameters.InventurID}`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.dsoLagerort = result.value[0];

      this.datalistLagerorte.load();
    }, (result: any) => {

    });

    this.onClickAuswahlLagerorte = () => {
    this.buttonOpenDialogAuswahlLagerorteClick('');
};


  }

  buttonArtikelAuswahlClick(event: any) {
    this.dialogService.open(ErfassenArtikelAuswahlComponent, { parameters: {}, title: `Artikel` });
  }

  button2Click(event: any) {
    this.notificationService.notify({ severity: "success", summary: ``, detail: `Artikel gezählt!`, duration: 50000 });
  }

  datalistLagerorteLoadData(event: any) {
    this.dbOptimo.getInventurBases(null, null, null, `LagerortNummer`, null, null, null, null)
    .subscribe((result: any) => {
      this.rstLagerorte = result.value;

      this.rstLagerorteCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  buttonOpenDialogAuswahlLagerorteClick(event: any) {
    this.dialogService.open(ZzErfassenAuswahlLagerorteComponent, { parameters: {}, title: `Auswahl Lagerorte` })
        .afterClosed().subscribe(result => {
              if (result != null) {
              this.dbOptimo.getInventurBases(`InventurID eq ${result}`, null, null, null, null, null, null, null)
        .subscribe((result: any) => {
              this.dsoLagerort = result.value[0];
        }, (result: any) => {
      
        });
      }
    });
  }
}
